### PR TITLE
HCG color model support

### PR DESCRIPTION
**Pull request by acterhd**
I not unit tested, but already write first HCG support for D3. 

https://github.com/acterhd/hcg-color

### CODE REVIEW

**Comment by mbostock** [comment]
I’d prefer this as an optional color space plugin along the lines of d3-hsv:

https://github.com/d3/d3-hsv

Would you be willing to create a repo with the same structure for d3-hcg? I
could create one in the d3 org and add you as a collaborator if it helps.

**Comment by acterhd** [comment]
I'm have no unit tests, in internet have no HCG calculators now. I want to write own `RGB<=>HCG` calculator.

**Comment by mbostock** [comment]
It would be your repository, so the decision of whether you want to write
unit tests is yours.

**Comment by acterhd** [comment]
Try to another branch. I don't know how to move to another repo/branch. I use Github for Windows.
https://github.com/acterhd/d3-hcg

**Comment by curran** [comment]
@acterhd The idea is that you can create a completely new repository, rather than add your code to d3-color.

I suggest you make a new repository under https://github.com/acterhd/d3-hcg using the GitHub user interface.

image

Then clone it, and from there follow the instructions found in [Let’s Make a (D3) Plugin](https://bost.ocks.org/mike/d3-plugin/). Once you have the basic structure from there, you can then re-implement the code from this PR inside that new repository.

I recently did a similar process to create [d3-tile](https://github.com/d3/d3-tile).

**Comment by acterhd** [comment]
Repository now by mbostock

**Comment by curran** [comment]
Ahh I see. Sorry, I didn't realize - you did all those steps and now the repository has been transferred to https://github.com/mbostock/d3-hcg. Got it.

It looks good!

**Comment by mbostock** [comment]
Moved to https://github.com/d3/d3-hcg and added both of you as collaborators.

**Pull request closed without merging**
